grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
model_selection:
  module_0:
    class: LinearRegression
    module: sklearn.linear_model
    params:
      fit_intercept: true
    search_param_grid:
      fit_intercept:
      - true
      - false
  module_1:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      min_samples_leaf: 3
    search_param_grid:
      min_samples_leaf:
      - 6
      - 3
      max_depth:
      - 3
      - 5
  module_2:
    class: DecisionTreeRegressor
    module: sklearn.tree
    params:
      min_samples_leaf: 3
    search_param_grid:
      min_samples_leaf:
      - 6
      - 15
      - 30
      max_features:
      - 1
      - sqrt
      max_leaf_nodes:
      - 5
      - 15
      - 50
      splitter:
      - best
      - random
